FORMAT: 1A

# Glo Currency | Project P

# Country [/api/v1/r1/countries]

## Get available countries. [GET]
Return available countries for the current user. 
Live and Sandbox users can have different countries available.

+ Request (application/json)
    + Headers
    
            Accept: application/json
            Authorization: Bearer: valid-api-token

+ Response 200 (application/json)
    + Body

            {
                "status": "SUCCESS",
                "countries": [
                    {
                        "country_code": "CM",
                        "status": true
                    },
                    {
                        "country_code": "GM",
                        "status": true
                    }
                ]
            }
            
+ Response 401 (application/json)
    + Body

            {
                "status": "FAIL",
                "message": "Unauthenticated." 
            }
            
            
# Transaction [/api/v1/r1/transaction]

## Get payout transactions. [GET /api/v1/r1/{country_code}/transactions]
Get all transactions that have been assigned for
payout.

+ Parameters
    + country_code: `CM` (string, required) - Country code.

+ Request (application/json)
    + Headers

            Authorization: Bearer: valid-api-token

+ Response 200 (application/json)
    + Body

            {
                "status": "SUCCESS",
                "transactions": [update
                    {
                        "status": "HQ_OK",
                        "transaction_id": "GC1234567890"
                    }
                ]
            }

## Get transaction details. [GET /api/v1/r1/{country_code}/transaction/{transaction_id}]
Get details of a single transaction.

+ Parameters
    + country_code: `CM` (string, required) - Country code.
    + transaction_id: `GC1234567890` (string, required) - Transaction ID.

+ Request (application/json)
    + Headers
            
            Accept: application/json
            Authorization: Bearer: api-token

+ Response 200 (application/json)
    + Body

            {
                "status": "SUCCESS",
                "transaction": {
                    "status": "HQ_OK",
                    "transaction_id": "GC1234567890"
                }
            }

            
## Accept payout transaction. [POST /api/v1/r1/{country_code}/transaction/{transaction_id}/accept]
Accept transaction so that the Bank/Agent can pay them out to beneficiaries.

+ Parameters
    + country_code: `CM` (string, required) - Country code.
    + transaction_id: `GC1234567890` (string, required) - Transaction ID.

+ Request (application/json)
    + Headers

            Authorization: Bearer: api-token

+ Response 200 (application/json)
    + Body

            {
                "status": "SUCCESS",
                "transaction_id": "GC1234567890"
            }
            
## Process payout transaction. [POST /api/v1/r1/{country_code}/transaction/{transaction_id}/process]
Inform the system that a transaction that was accepted by the Bank/Agent for payout has paid out and should be marked as processed with the
details provided.

+ Parameters
    + country_code: `CM` (string, required) - Country code.
    + transaction_id: `GC1234567890` (string, required) - Transaction ID.

+ Request (application/json)
    + Headers

            Authorization: Bearer: api-token

+ Response 200 (application/json)
    + Body

            {
                "status": "SUCCESS",
                "transaction_id": "GC1234567890"
            }